name: Deploy AWS Infrastructure with Terraform

on:
  push:
    tags:
      - 'deploy-dev'
      - 'deploy-prod'

  workflow_dispatch:
    inputs:
      stage:
        description: 'Select Deployment Stage (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  TERRAFORM_VERSION: "1.7.5"
  AWS_REGION: "ap-south-2"
  AWS_SDK_LOAD_CONFIG: "1"
  S3_BACKEND_BUCKET_NAME: "terraform-state-buckettt"

jobs:
  deploy_or_update:
    runs-on: [self-hosted, ubuntu, ec2]
    permissions:
      contents: read
    timeout-minutes: 30

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Lambda Deployment Packages
        run: chmod +x userscripts/build_lambda_zips.sh && ./userscripts/build_lambda_zips.sh
        working-directory: ./

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Determine Deployment Stage and Select/Create Terraform Workspace
        id: set_stage_and_workspace
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            if [[ "$TAG_NAME" == "deploy-dev" ]]; then STAGE="dev"
            elif [[ "$TAG_NAME" == "deploy-prod" ]]; then STAGE="prod"
            else
              echo "Unsupported tag name. Exiting."; exit 1;
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            STAGE="${{ github.event.inputs.stage }}"
          fi
          echo "STAGE=$STAGE" >> $GITHUB_ENV
          echo "LOG_FILE=/home/ubuntu/runnerlog/${STAGE}/${STAGE}_${{ github.run_id }}.log" >> $GITHUB_ENV

          terraform init \
            -backend-config="bucket=${{ env.S3_BACKEND_BUCKET_NAME }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="key=terraform/${STAGE}/terraform.tfstate"

          if terraform workspace list | grep -q " ${STAGE}$"; then
            terraform workspace select "$STAGE"
          else
            terraform workspace new "$STAGE"
          fi
        working-directory: ./Terraform

      - name: Select tfvars file for stage
        run: |
          if [[ "$STAGE" == "dev" ]]; then
            TFVARS_FILE="../configs/dev.tfvars"
          elif [[ "$STAGE" == "prod" ]]; then
            TFVARS_FILE="../configs/prod.tfvars"
          else
            echo "Unknown stage $STAGE"; exit 1
          fi
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
        working-directory: ./Terraform

      - name: Terraform Validate
        run: terraform validate | tee -a "$LOG_FILE"
        working-directory: ./Terraform

      - name: Terraform Plan
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: terraform plan -var-file=${{ env.TFVARS_FILE }} -var="ec2_ssh_private_key=${EC2_SSH_PRIVATE_KEY}" -out=tfplan | tee -a "$LOG_FILE"
        working-directory: ./Terraform

      - name: Simulate Failure for Alert Testing
        run: |
          echo "Simulating failure to test alert notifications..." | tee -a "$LOG_FILE"
          exit 1

      - name: Terraform Apply & Capture Output
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: terraform apply -auto-approve tfplan | tee -a "$LOG_FILE"
        working-directory: ./Terraform

      - name: Get EC2 Public IP/DNS
        run: |
          PUBLIC_IP=$(terraform output -raw instance_public_ip)
          if [ -z "$PUBLIC_IP" ]; then
            echo "ERROR: No public IP found." | tee -a "$LOG_FILE"
            exit 1
          fi
          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
        working-directory: ./Terraform

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Save Terraform Apply Output to EC2 Log Directory
        run: |
          echo "=== Terraform Apply Log (${STAGE}) ===" >> "$LOG_FILE"
          cat ./Terraform/tfplan_output.log >> "$LOG_FILE"
        continue-on-error: true

      - name: Validate Application Health Post-Deployment
        if: success() && env.EC2_PUBLIC_IP != ''
        run: |
          echo "Checking health at http://${{ env.EC2_PUBLIC_IP }}/actuator/health..." | tee -a "$LOG_FILE"
          for i in {1..40}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://${{ env.EC2_PUBLIC_IP }}/actuator/health")
            echo "Retry $i: HTTP $STATUS" | tee -a "$LOG_FILE"
            if [ "$STATUS" -eq 200 ]; then
              echo "App is healthy." | tee -a "$LOG_FILE"
              exit 0
            fi
            sleep 30
          done
          echo "App did not become healthy." | tee -a "$LOG_FILE"
          exit 1
